[package]
name = "argon2_pswd"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
rand_core = { version = "0.6", features = ["getrandom"] }
clap = { version = "4.4", features = ["derive"] }